# Generated by Django 3.1.3 on 2021-04-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210428_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='the sku', max_length=20, unique=True, verbose_name='Stock keeping unit'),
            preserve_default=False,
        ),
    ]
