# Generated by Django 3.1.3 on 2021-04-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_count',
            field=models.IntegerField(help_text='How many items are currently in stock'),
        ),
    ]
